# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-01-18 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='name',
            new_name='chapter',
        ),
        migrations.AlterField(
            model_name='course',
            name='degree',
            field=models.CharField(choices=[('primary_level', '\u521d\u7ea7'), ('middle_level', '\u4e2d\u7ea7'), ('high_level', '\u9ad8\u7ea7')], max_length=20, verbose_name='\u96be\u5ea6'),
        ),
    ]
