# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-01-18 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20180118_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(upload_to='apps/course/%Y/%m', verbose_name='\u5c01\u9762\u56fe'),
        ),
        migrations.AlterField(
            model_name='courseresource',
            name='download',
            field=models.FileField(upload_to='apps/course/resourcee/%Y%m', verbose_name='\u8d44\u6e90\u6587\u4ef6'),
        ),
    ]
